:- dynamic(discardPile/1).
:- dynamic(urutanPemain/1).
:- dynamic(jumlahPemain/1).
:- dynamic(reverseGiliran/1).
:- dynamic(infoPemain/2).
:- dynamic(idxGiliran/1).
:- dynamic(playedDraw/0).
:- dynamic(playedDrawFour/0).
:- dynamic(uniCalled/1).
:- dynamic(drawPile/1).
:- dynamic(startGame/1).