:- dynamic(discardPile/1).
:- dynamic(urutanPemain/1).
:- dynamic(jumlahPemain/1).
:- dynamic(reverseGiliran/1).
:- dynamic(infoPemain/2).
:- dynamic(idxGiliran/1).
:- dynamic(playedDraw/0).
:- dynamic(playedDrawFour/0).
:- dynamic(uniCalled/1).
:- dynamic(drawPile/1).
:- dynamic(warnaActive/1).
:- dynamic(startedGame/1).
:- dynamic(hide/2).
:- dynamic(prevWarnaActive/1).
:- dynamic(kartuAksiTerakhir/1).